### ISSUE TITLE
erro na api

### ISSUE THREAD

**Issue by zanfranceschi** [thales-maciel/hampshire#1]
Amigo, sua api deu essa zica aqui:

`api1_1   | Error migratingConnectionUsageError (Just "could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432?\n")`

Vamo deixar o haskellzin bem na rinha!!!

**Comment by thales-maciel** [comment]
opa! vou atualizar!!

**Comment by thales-maciel** [comment]
atualizado dia 16 com a mesma tag (latest)
